/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIS = 4;
  /** RegularExpression Id. */
  int MENOS = 5;
  /** RegularExpression Id. */
  int VEZES = 6;
  /** RegularExpression Id. */
  int DIVIDIDO = 7;
  /** RegularExpression Id. */
  int ELEVADO = 8;
  /** RegularExpression Id. */
  int ATRIBUICAO = 9;
  /** RegularExpression Id. */
  int IGUAL = 10;
  /** RegularExpression Id. */
  int DIFERENTE = 11;
  /** RegularExpression Id. */
  int MAIOR = 12;
  /** RegularExpression Id. */
  int MENOR = 13;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 14;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 15;
  /** RegularExpression Id. */
  int OU = 16;
  /** RegularExpression Id. */
  int E = 17;
  /** RegularExpression Id. */
  int FIM_PROGRAMA = 18;
  /** RegularExpression Id. */
  int FIM_LINHA = 19;
  /** RegularExpression Id. */
  int VIRGULA = 20;
  /** RegularExpression Id. */
  int INICIO_BLOCO = 21;
  /** RegularExpression Id. */
  int FIM_BLOCO = 22;
  /** RegularExpression Id. */
  int INICIO_OPERACAO_LINHA = 23;
  /** RegularExpression Id. */
  int FIM_OPERACAO_LINHA = 24;
  /** RegularExpression Id. */
  int DEFINICAO_DE_FUNCAO = 25;
  /** RegularExpression Id. */
  int ABRE_PARENTESE = 26;
  /** RegularExpression Id. */
  int FECHA_PARENTESE = 27;
  /** RegularExpression Id. */
  int LOQUEANDO = 28;
  /** RegularExpression Id. */
  int REPETECO = 29;
  /** RegularExpression Id. */
  int MIN_REPETECO = 30;
  /** RegularExpression Id. */
  int MAX_REPETECO = 31;
  /** RegularExpression Id. */
  int SE = 32;
  /** RegularExpression Id. */
  int SENAO = 33;
  /** RegularExpression Id. */
  int REDONDO = 34;
  /** RegularExpression Id. */
  int QUEBRADO = 35;
  /** RegularExpression Id. */
  int TROVA = 36;
  /** RegularExpression Id. */
  int LOGICO = 37;
  /** RegularExpression Id. */
  int VAZIO = 38;
  /** RegularExpression Id. */
  int BOOLEANO = 39;
  /** RegularExpression Id. */
  int NOME_VARIAVEL = 40;
  /** RegularExpression Id. */
  int NOME_FUNCAO = 41;
  /** RegularExpression Id. */
  int LETRA = 42;
  /** RegularExpression Id. */
  int MINUSCULAS = 43;
  /** RegularExpression Id. */
  int MAIUSCULAS = 44;
  /** RegularExpression Id. */
  int NUMERO = 45;
  /** RegularExpression Id. */
  int DIGITO = 46;
  /** RegularExpression Id. */
  int TEXTO = 47;
  /** RegularExpression Id. */
  int ASCII = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"< \"",
    "\">=\"",
    "\"<=\"",
    "\"ou\"",
    "\"e\"",
    "\"pareHome\"",
    "\"\\n\"",
    "\",\"",
    "\"tche\"",
    "\"bah\"",
    "\"dai\"",
    "\"ne\"",
    "\"funcao\"",
    "\"(\"",
    "\")\"",
    "\"loqueando\"",
    "\"repeteco\"",
    "\"de\"",
    "\"ate\"",
    "\"se\"",
    "\"senao\"",
    "\"redondo\"",
    "\"quebrado\"",
    "\"trova\"",
    "\"logico\"",
    "\"vazio\"",
    "<BOOLEANO>",
    "<NOME_VARIAVEL>",
    "<NOME_FUNCAO>",
    "<LETRA>",
    "<MINUSCULAS>",
    "<MAIUSCULAS>",
    "<NUMERO>",
    "<DIGITO>",
    "<TEXTO>",
    "<ASCII>",
  };

}
