/* Generated By:JavaCC: Do not edit this line. LexerTreeConstants.java Version 5.0 */
public interface LexerTreeConstants
{
  public int JJTMAIN = 0;
  public int JJTMAIS = 1;
  public int JJTMENOS = 2;
  public int JJTVEZES = 3;
  public int JJTDIVIDIDO = 4;
  public int JJTELEVADO = 5;
  public int JJTRESTO = 6;
  public int JJTMAIOR = 7;
  public int JJTMENOR = 8;
  public int JJTMAIORIGUAL = 9;
  public int JJTMENORIGUAL = 10;
  public int JJTIGUAL = 11;
  public int JJTDIFERENTE = 12;
  public int JJTOU = 13;
  public int JJTE = 14;
  public int JJTNEGACAO = 15;
  public int JJTLOQUEANDO = 16;
  public int JJTREPETECO = 17;
  public int JJTTCHE = 18;
  public int JJTBAH = 19;
  public int JJTDAI = 20;
  public int JJTDE = 21;
  public int JJTATE = 22;
  public int JJTSE = 23;
  public int JJTSENAO = 24;
  public int JJTFUNCAO = 25;
  public int JJTDEVOLTA = 26;
  public int JJTTROVAR = 27;
  public int JJTESCUITAR = 28;
  public int JJTFIMDEARQUIVO = 29;
  public int JJTPAREHOME = 30;
  public int JJTSIMBOLOATRIBUICAO = 31;
  public int JJTABREPARENTESE = 32;
  public int JJTFECHAPARENTESE = 33;
  public int JJTFIMLINHA = 34;
  public int JJTVIRGULA = 35;
  public int JJTREDONDO = 36;
  public int JJTQUEBRADO = 37;
  public int JJTTROVA = 38;
  public int JJTLOGICO = 39;
  public int JJTVAZIO = 40;
  public int JJTNOMEVARIAVEL = 41;
  public int JJTNOMEFUNCAO = 42;
  public int JJTTEXTO = 43;
  public int JJTNUMEROCOMSINAL = 44;
  public int JJTBOOLEANO = 45;
  public int JJTLINHA = 46;
  public int JJTELEMENTODELINHA = 47;
  public int JJTBLOCO = 48;
  public int JJTATRIBUICAO = 49;
  public int JJTLACODEATRIBUICAO = 50;
  public int JJTEXPRESSAO = 51;
  public int JJTATRIBUIVEL = 52;
  public int JJTOPERADOR = 53;
  public int JJTOPERADORMATEMATICO = 54;
  public int JJTOPERADORLOGICO = 55;
  public int JJTCONECTORLOGICO = 56;
  public int JJTEXPRESSAOMATEMATICA = 57;
  public int JJTLACOMATEMATICO = 58;
  public int JJTATRIBUIVELMATEMATICO = 59;
  public int JJTEXPRESSAOLOGICA = 60;
  public int JJTEXPRESSAOLOGICAENTREPARENTESES = 61;
  public int JJTLACOLOGICO = 62;
  public int JJTVERIFICACAODENOME = 63;
  public int JJTOPCOESDENOME = 64;
  public int JJTLIGACAOLOGICA = 65;
  public int JJTPRIMITIVOSLOGICOS = 66;
  public int JJTDECLARACAODEVARIAVEL = 67;
  public int JJTTIPODEDADO = 68;
  public int JJTLISTADEDECLARACAO = 69;
  public int JJTCHAMADADEFUNCAO = 70;
  public int JJTPASSAGEMDEPARAMETROS = 71;
  public int JJTFUNCOESNATIVAS = 72;
  public int JJTFUNCAOTROVAR = 73;
  public int JJTFUNCAOESCUITAR = 74;
  public int JJTRETORNODEFUNCAO = 75;
  public int JJTINICIODOLOQUEANDO = 76;
  public int JJTINICIODOREPETECO = 77;
  public int JJTMEIOBLOCOREPETICAO = 78;
  public int JJTFIMBLOCOREPETICAO = 79;
  public int JJTINICIOSE = 80;
  public int JJTSEDEUMALINHA = 81;
  public int JJTBLOCOSE = 82;
  public int JJTINICIOSENAO = 83;
  public int JJTFIMBLOCOSENAO = 84;
  public int JJTDEFINICAODEFUNCAO = 85;
  public int JJTTIPODERETORNO = 86;
  public int JJTDEFINICAODEPARAMETROS = 87;
  public int JJTMEIODEFUNCAO = 88;
  public int JJTBLOCODEFUNCAO = 89;


  public String[] jjtNodeName = {
    "main",
    "mais",
    "menos",
    "vezes",
    "dividido",
    "elevado",
    "resto",
    "maior",
    "menor",
    "maiorIgual",
    "menorIgual",
    "igual",
    "diferente",
    "ou",
    "e",
    "negacao",
    "loqueando",
    "repeteco",
    "tche",
    "bah",
    "dai",
    "de",
    "ate",
    "se",
    "senao",
    "funcao",
    "devolta",
    "trovar",
    "escuitar",
    "fimDeArquivo",
    "pareHome",
    "simboloAtribuicao",
    "abreParentese",
    "fechaParentese",
    "fimLinha",
    "virgula",
    "redondo",
    "quebrado",
    "trova",
    "logico",
    "vazio",
    "nomeVariavel",
    "nomeFuncao",
    "texto",
    "numeroComSinal",
    "booleano",
    "linha",
    "elementoDeLinha",
    "bloco",
    "atribuicao",
    "lacoDeAtribuicao",
    "expressao",
    "atribuivel",
    "operador",
    "operadorMatematico",
    "operadorLogico",
    "conectorLogico",
    "expressaoMatematica",
    "lacoMatematico",
    "atribuivelMatematico",
    "expressaoLogica",
    "expressaoLogicaEntreParenteses",
    "lacoLogico",
    "verificacaoDeNome",
    "opcoesDeNome",
    "ligacaoLogica",
    "primitivosLogicos",
    "declaracaoDeVariavel",
    "tipoDeDado",
    "listaDeDeclaracao",
    "chamadaDeFuncao",
    "passagemDeParametros",
    "funcoesNativas",
    "funcaoTrovar",
    "funcaoEscuitar",
    "retornoDeFuncao",
    "inicioDoLoqueando",
    "inicioDoRepeteco",
    "meioBlocoRepeticao",
    "fimBlocoRepeticao",
    "inicioSe",
    "seDeUmaLinha",
    "blocoSe",
    "inicioSenao",
    "fimBlocoSenao",
    "definicaoDeFuncao",
    "tipoDeRetorno",
    "definicaoDeParametros",
    "meioDeFuncao",
    "blocoDeFuncao",
  };
}
/* JavaCC - OriginalChecksum=cbe4ea4ed43d8010ac648280edd808ca (do not edit this line) */
