/* Generated By:JJTree&JavaCC: Do not edit this line. LexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int MAIS = 9;
  /** RegularExpression Id. */
  int MENOS = 10;
  /** RegularExpression Id. */
  int VEZES = 11;
  /** RegularExpression Id. */
  int DIVIDIDO = 12;
  /** RegularExpression Id. */
  int ELEVADO = 13;
  /** RegularExpression Id. */
  int ATRIBUICAO = 14;
  /** RegularExpression Id. */
  int IGUAL = 15;
  /** RegularExpression Id. */
  int DIFERENTE = 16;
  /** RegularExpression Id. */
  int MAIOR = 17;
  /** RegularExpression Id. */
  int MENOR = 18;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 19;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 20;
  /** RegularExpression Id. */
  int OU = 21;
  /** RegularExpression Id. */
  int E = 22;
  /** RegularExpression Id. */
  int FIM_PROGRAMA = 23;
  /** RegularExpression Id. */
  int FIM_LINHA = 24;
  /** RegularExpression Id. */
  int VIRGULA = 25;
  /** RegularExpression Id. */
  int INICIO_BLOCO = 26;
  /** RegularExpression Id. */
  int FIM_BLOCO = 27;
  /** RegularExpression Id. */
  int INICIO_OPERACAO_LINHA = 28;
  /** RegularExpression Id. */
  int FIM_OPERACAO_LINHA = 29;
  /** RegularExpression Id. */
  int FUNCAO = 30;
  /** RegularExpression Id. */
  int ABRE_PARENTESE = 31;
  /** RegularExpression Id. */
  int FECHA_PARENTESE = 32;
  /** RegularExpression Id. */
  int LOQUEANDO = 33;
  /** RegularExpression Id. */
  int REPETECO = 34;
  /** RegularExpression Id. */
  int MIN_REPETECO = 35;
  /** RegularExpression Id. */
  int MAX_REPETECO = 36;
  /** RegularExpression Id. */
  int SE = 37;
  /** RegularExpression Id. */
  int SENAO = 38;
  /** RegularExpression Id. */
  int TROVAR = 39;
  /** RegularExpression Id. */
  int REDONDO = 40;
  /** RegularExpression Id. */
  int QUEBRADO = 41;
  /** RegularExpression Id. */
  int TROVA = 42;
  /** RegularExpression Id. */
  int LOGICO = 43;
  /** RegularExpression Id. */
  int VAZIO = 44;
  /** RegularExpression Id. */
  int BOOLEANO = 45;
  /** RegularExpression Id. */
  int NOME_VARIAVEL = 46;
  /** RegularExpression Id. */
  int NOME_FUNCAO = 47;
  /** RegularExpression Id. */
  int LETRA = 48;
  /** RegularExpression Id. */
  int MINUSCULAS = 49;
  /** RegularExpression Id. */
  int MAIUSCULAS = 50;
  /** RegularExpression Id. */
  int NUMERO = 51;
  /** RegularExpression Id. */
  int DIGITO = 52;
  /** RegularExpression Id. */
  int TEXTO = 53;
  /** RegularExpression Id. */
  int ASCII = 54;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"//\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 8>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"< \"",
    "\">=\"",
    "\"<=\"",
    "\"ou\"",
    "\"e\"",
    "\"pareHome\"",
    "\"\\n\"",
    "\",\"",
    "\"tche\"",
    "\"bah\"",
    "\"dai\"",
    "\"ne\"",
    "\"funcao\"",
    "\"(\"",
    "\")\"",
    "\"loqueando\"",
    "\"repeteco\"",
    "\"de\"",
    "\"ate\"",
    "\"se\"",
    "\"senao\"",
    "\"Trovar\"",
    "\"redondo\"",
    "\"quebrado\"",
    "\"trova\"",
    "\"logico\"",
    "\"vazio\"",
    "<BOOLEANO>",
    "<NOME_VARIAVEL>",
    "<NOME_FUNCAO>",
    "<LETRA>",
    "<MINUSCULAS>",
    "<MAIUSCULAS>",
    "<NUMERO>",
    "<DIGITO>",
    "<TEXTO>",
    "<ASCII>",
  };

}
