/* Generated By:JavaCC: Do not edit this line. LexerTreeConstants.java Version 5.0 */
public interface LexerTreeConstants
{
  public int JJTMAIN = 0;
  public int JJTMAIS = 1;
  public int JJTMENOS = 2;
  public int JJTVEZES = 3;
  public int JJTDIVIDIDO = 4;
  public int JJTELEVADO = 5;
  public int JJTRESTO = 6;
  public int JJTMAIOR = 7;
  public int JJTMENOR = 8;
  public int JJTMAIORIGUAL = 9;
  public int JJTMENORIGUAL = 10;
  public int JJTIGUAL = 11;
  public int JJTDIFERENTE = 12;
  public int JJTOU = 13;
  public int JJTE = 14;
  public int JJTNEGACAO = 15;
  public int JJTLOQUEANDO = 16;
  public int JJTREPETECO = 17;
  public int JJTTCHE = 18;
  public int JJTBAH = 19;
  public int JJTDAI = 20;
  public int JJTDE = 21;
  public int JJTATE = 22;
  public int JJTSE = 23;
  public int JJTSENAO = 24;
  public int JJTFUNCAO = 25;
  public int JJTTROVAR = 26;
  public int JJTFIMDEARQUIVO = 27;
  public int JJTPAREHOME = 28;
  public int JJTSIMBOLOATRIBUICAO = 29;
  public int JJTABREPARENTESE = 30;
  public int JJTFECHAPARENTESE = 31;
  public int JJTFIMLINHA = 32;
  public int JJTVIRGULA = 33;
  public int JJTREDONDO = 34;
  public int JJTQUEBRADO = 35;
  public int JJTTROVA = 36;
  public int JJTLOGICO = 37;
  public int JJTVAZIO = 38;
  public int JJTNOMEVARIAVEL = 39;
  public int JJTNOMEFUNCAO = 40;
  public int JJTTEXTO = 41;
  public int JJTNUMEROCOMSINAL = 42;
  public int JJTBOOLEANO = 43;
  public int JJTLINHA = 44;
  public int JJTELEMENTODELINHA = 45;
  public int JJTATRIBUICAO = 46;
  public int JJTLACODEATRIBUICAO = 47;
  public int JJTEXPRESSAOMATEMATICA = 48;
  public int JJTLACOMATEMATICO = 49;
  public int JJTATRIBUIVELMATEMATICO = 50;
  public int JJTOPERADORMATEMATICO = 51;
  public int JJTEXPRESSAOLOGICA = 52;
  public int JJTEXPRESSAOLOGICAENTREPARENTESES = 53;
  public int JJTLACOLOGICO = 54;
  public int JJTCONECTORLOGICO = 55;
  public int JJTVERIFICACAODEVARIAVEL = 56;
  public int JJTLIGACAOLOGICA = 57;
  public int JJTOPERADORLOGICO = 58;
  public int JJTEXPRESSAO = 59;
  public int JJTATRIBUIVEL = 60;
  public int JJTOPERADOR = 61;
  public int JJTDECLARACAODEVARIAVEL = 62;
  public int JJTTIPODEDADO = 63;
  public int JJTLISTADEDECLARACAO = 64;
  public int JJTBLOCO = 65;
  public int JJTINICIODOLOQUEANDO = 66;
  public int JJTMEIODOLOQUEANDO = 67;
  public int JJTBLOCODOLOQUEANDO = 68;
  public int JJTINICIODOREPETECO = 69;
  public int JJTMEIODOREPETECO = 70;
  public int JJTBLOCODOREPETECO = 71;
  public int JJTINICIOSE = 72;
  public int JJTSEDEUMALINHA = 73;
  public int JJTBLOCOSE = 74;
  public int JJTINICIOSENAO = 75;
  public int JJTFIMBLOCOSENAO = 76;
  public int JJTDEFINICAODEFUNCAO = 77;
  public int JJTTIPODERETORNO = 78;
  public int JJTDEFINICAODEPARAMETROS = 79;
  public int JJTMEIODEFUNCAO = 80;
  public int JJTBLOCODEFUNCAO = 81;
  public int JJTCHAMADADEFUNCAO = 82;
  public int JJTPASSAGEMDEPARAMETROS = 83;
  public int JJTPARAMETROSATRIBUIVEIS = 84;
  public int JJTFUNCAOTROVAR = 85;


  public String[] jjtNodeName = {
    "main",
    "mais",
    "menos",
    "vezes",
    "dividido",
    "elevado",
    "resto",
    "maior",
    "menor",
    "maiorIgual",
    "menorIgual",
    "igual",
    "diferente",
    "ou",
    "e",
    "negacao",
    "loqueando",
    "repeteco",
    "tche",
    "bah",
    "dai",
    "de",
    "ate",
    "se",
    "senao",
    "funcao",
    "trovar",
    "fimDeArquivo",
    "pareHome",
    "simboloAtribuicao",
    "abreParentese",
    "fechaParentese",
    "fimLinha",
    "virgula",
    "redondo",
    "quebrado",
    "trova",
    "logico",
    "vazio",
    "nomeVariavel",
    "nomeFuncao",
    "texto",
    "numeroComSinal",
    "booleano",
    "linha",
    "elementoDeLinha",
    "atribuicao",
    "lacoDeAtribuicao",
    "expressaoMatematica",
    "lacoMatematico",
    "atribuivelMatematico",
    "operadorMatematico",
    "expressaoLogica",
    "expressaoLogicaEntreParenteses",
    "lacoLogico",
    "conectorLogico",
    "verificacaoDeVariavel",
    "ligacaoLogica",
    "operadorLogico",
    "expressao",
    "atribuivel",
    "operador",
    "declaracaoDeVariavel",
    "tipoDeDado",
    "listaDeDeclaracao",
    "bloco",
    "inicioDoLoqueando",
    "meioDoLoqueando",
    "blocoDoLoqueando",
    "inicioDoRepeteco",
    "meioDoRepeteco",
    "blocoDoRepeteco",
    "inicioSe",
    "seDeUmaLinha",
    "blocoSe",
    "inicioSenao",
    "fimBlocoSenao",
    "definicaoDeFuncao",
    "tipoDeRetorno",
    "definicaoDeParametros",
    "meioDeFuncao",
    "blocoDeFuncao",
    "chamadaDeFuncao",
    "passagemDeParametros",
    "parametrosAtribuiveis",
    "funcaoTrovar",
  };
}
/* JavaCC - OriginalChecksum=28138e774a85d486cc364d98eafd4fa4 (do not edit this line) */
